name: Reverse Proxy
version: "1.0.0"
slug: reverse_proxy
description: Simple reverse proxy written in Go with configurable target URL
arch:
  - amd64
startup: application
boot: auto
options:
  target_url: "http://example.com"
schema:
  target_url: str
ports:
  8080/tcp: 8080
