name: Reverse Proxy 2
version: "1.0.1"
slug: reverse_proxy_2
description: Simple reverse proxy written in Go with configurable target URL
arch:
  - amd64
startup: application
boot: auto
options:
  target_url: "http://example.com"
schema:
  target_url: str
ingress: true
ingress_port: 8080
panel_icon: mdi:proxy
